<?php
/** @var $block \Rangerz\Quicklink\Block\QuickLink */
/** @var $viewModel \Rangerz\Quicklink\ViewModel\QuickLink */
$viewModel = $block->getViewModel();
?>
<!-- BEGIN GOOGLE QUICKLINK CODE -->
<script>
    require([
        'quicklink',
        'Rangerz_Quicklink/js/options-resolver',
        'polyfillio',
        'domReady!'
    ], function (quicklink, resolver) {
        var options = resolver(<?= /* @noEscape */ $viewModel->getOptions() ?>);
        quicklink.listen(options);
    });
</script>
<!-- END GOOGLE QUICKLINK CODE -->
